spring:
  main:
    allow-circular-references: false
  application:
    name: autorizador

  cloud:
    aws:
      region: sa-east-1
      stack:
        auto: false
      credentials:
        accessKey: test
        accessKeyaccessKey: test
      sqs:
        endpoint: http://localhost:4566

  datasource:
    url: jdbc:mysql://localhost:3307/authorizer?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # or 'create', 'create-drop', 'none'
    show-sql: false
